version: "3"
services:
  mf-luigi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 9000:9000
    command:
      sh -c 'yarn && yarn start'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    user: "1000:1000"

