version: "3"
services:
  mf-luigi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 4200:4200
    command:
      sh -c 'npm i && ng serve -o --host 0.0.0.0'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    user: "1000:1000"

